var TREE_TPL = {
  "target" : "frameset",
  "icon_e" : "icons/empty.gif",
  "icon_l" : "icons/empty.gif",
  "icon_32" : "icons/base.gif",
  "icon_36" : "icons/base.gif",
  "icon_48" : "icons/base.gif",
  "icon_52" : "icons/base.gif",
  "icon_56" : "icons/base.gif",
  "icon_60" : "icons/base.gif",
  "icon_16" : "icons/page.gif",
  "icon_20" : "icons/page.gif",
  "icon_24" : "icons/page.gif",
  "icon_28" : "icons/page.gif",
  "icon_0" : "icons/page.gif",
  "icon_4" : "icons/page.gif",
  "icon_2" : "icons/empty.gif",
  "icon_3" : "icons/empty.gif",
  "icon_18" : "icons/plusbottom.gif",
  "icon_19" : "icons/empty.gif",
  "icon_26" : "icons/minusbottom.gif",
  "icon_27" : "icons/empty.gif"
};